cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIA3JC324U26VQVL7YR
      secret-key: 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

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
